apiVersion: v1
kind: Service
metadata:
  name: volume-service
spec:
  selector:
    app : volume-pod
  ports:
    - protocol: 'TCP' 
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-deployment
spec:
  replicas: 2
  selector:
    # matchExpressions:
    #   - {key: app,operator: In ,values: [volume-pod]}
    matchLabels:
      app : volume-pod
  template:
    metadata:
      labels:
        app : volume-pod 
      name: volume-pod
    spec:
      containers:
        - name: volume-containers
          image: mousanageh/kub-first-app:2
          imagePullPolicy: Always
          volumeMounts: 
            - mountPath: /app/story
              name: story-volume
      volumes:
      
        # - name: story-volume-claim
          # emptyDir: {}
        
        # - name: story-volume-claim
        #   hostPath:
        #     path: /story-path
        #     type: DirectoryOrCreate
        
        - name: story-volume
          persistentVolumeClaim:
            claimName: story-volume-claim
