apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: story-volume-claim
spec:
  volumeName: story-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
