apiVersion: v1
kind: PersistentVolume
metadata:
  name: story-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany 
  hostPath:
    path: /story-path
    type: DirectoryOrCreate